spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev_todo
    username: dev_todo
    password: dev_todo
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        default_batch_fetch_size: 500
    database: mysql
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true