name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem

      - name: Deploy to Remote Server
        run: |
          ssh -i ~/.ssh/private_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} '
            export APP_DIR="${{ secrets.APP_DIR }}";
            export DB="${{ secrets.DB }}";
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}";
            export DB_USERNAME="${{ secrets.DB_USERNAME }}";
            export HOST="${{ secrets.HOST }}";
            bash -s
          ' < ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          APP_DIR: ${{ secrets.APP_DIR }}
          DB: ${{ secrets.DB }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          HOST: ${{ secrets.HOST }}
